name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64, Win32]
#        build_platform: [x64, Win32, ARM64] # Currently we don't have ARM64 helper files (like libssl-3-arm64.dll etc.)
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: MSBuild of plugin dll
      working-directory: vs.proj\
      run: msbuild NppPluginTemplate.vcxproj /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /p:PlatformToolset="v143"

    - name: Archive artifacts for x64
      if: matrix.build_platform == 'x64' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
          name: NppOpenAI_x64
          path: bin64\NppOpenAI.zip
#          name: plugin_dll_x64
#          path: bin64\NppOpenAI.dll

    - name: Archive artifacts for Win32
      if: matrix.build_platform == 'Win32' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
          name: NppOpenAI_x86
          path: bin\NppOpenAI.zip
#          name: plugin_dll_x86
#          path: bin\NppOpenAI.dll

#    - name: Archive artifacts for ARM64
#      if: matrix.build_platform == 'ARM64' && matrix.build_configuration == 'Release'
#      uses: actions/upload-artifact@v3
#      with:
#          name: plugin_dll_arm64
#          path: arm64\NppOpenAI.dll
